#!/bin/bash

WORKDIR="$(dirname -- "$(readlink -f -- "$0")")"

source ${WORKDIR}/conf/.env.ini
source ${WORKDIR}/script/common_func.sh

chkParameter $1
GETH_INSTANCE=$1


echo "=========================="
echo "geth monitoring..." ${GETH_INSTANCE}
echo "=========================="

bash  ${WORKDIR}/${GETH_INSTANCE}/3.mon_geth.sh

