#!/bin/bash

WORKDIR="$(dirname -- "$(readlink -f -- "$0")")"

source ${WORKDIR}/conf/.env.ini
source ${WORKDIR}/script/common_func.sh

cd ${WORKDIR}

for i in $(ls -d 85*);
do
    ./rstop ${i};
    sleep 1;
done


echo
echo "### Check Process #######################"
ps -ef | grep geth | grep 85

