#!/bin/bash

WORKDIR="$(dirname -- "$(readlink -f -- "$0")")"

source ${WORKDIR}/conf/.env.ini
source ${WORKDIR}/script/common_func.sh

chkParameter $1
GETH_INSTANCE=$1

WORKDIR="$(dirname -- "$(readlink -f -- "$0")")"

chkPID "${WORKDIR}/${GETH_INSTANCE}/geth.pid" "${GETH_INSTANCE}"

echo "=========================="
echo "geth Shutdowning..." ${GETH_INSTANCE}
echo "=========================="
echo

ps -ef | grep geth | grep ${GETH_INSTANCE}
echo

kill  `cat ${WORKDIR}/${GETH_INSTANCE}/geth.pid`
rm -rf ${WORKDIR}/${GETH_INSTANCE}/geth.pid

echo "Check Process...."
ps -ef | grep geth | grep ${GETH_INSTANCE}

