#!/bin/bash

WORKDIR="$(dirname -- "$(readlink -f -- "$0")")"

source ${WORKDIR}/conf/.env.ini
source ${WORKDIR}/script/common_func.sh

chkParameter $1
GETH_INSTANCE=$1
GETH_CMD=$2

WORKDIR="$(dirname -- "$(readlink -f -- "$0")")"

chkPID "${WORKDIR}/${GETH_INSTANCE}/geth.pid" "${GETH_INSTANCE}"

gethAttachLocal ${GETH_INSTANCE} ${GETH_CMD}

